#!/bin/bash
#  funcback.sh : Use $FUNCNAME
start(){
	echo $rootOrgSize
	local i=1
	while [ $i -le $rootOrgSize ] 
	do 
    # Print the values 
    createRootOrgCql $i $subOrgSize $rootOrgUserSize
    
      
    # increment the value 
    i=`expr $i + 1`
	done 
}

createRootOrgCql(){
	now=`date +%Y-%m-%d.%H:%M:%S%z`
	# echo $now
	local query="Insert into sunbird.organisation (id, orgName, channel, createddate, isrootorg,slug,status, hashtagid) values ('root-org-$1','root-org-name-$1','channel$1','$now',true,'channel$1',1,'channel$1');"
	echo $query
	local subOrgSize="$2"
	local rootOrgUserSize="$3"

	# echo $rootOrgSize
	if [ $1 == 1 ]
	then
		echo $query > $orgfile
	else
		echo $query >> $orgfile
	fi	
	local i=1

	while [ $i -le $subOrgSize ] 
	do 
    # Print the values 
    createSubOrgCql $1 $i
    
    # increment the value 
    i=`expr $i + 1`
	done 

	local j=1

	while [ $j -le $rootOrgUserSize ] 
	do 
    # Print the values 
    createUserForRootOrg $1 $j
    
    # increment the value 
    j=`expr $j + 1`
	done 

    createUserForRootOrgAsCreator $1 1
}

createSubOrgCql(){
	now=`date +%Y-%m-%d.%H:%M:%S%z`
	# echo $now
	local query="Insert into sunbird.organisation (id, orgName, channel, createddate, isrootorg,slug,status, hashtagid,rootorgid) values ('school-$1-$2','school-name-$1-$2','channel$1','$now',false,'channel$i',1,'channel$i','root-org-$1');"
	echo $query
	echo $query >> $orgfile
	createUserForSubOrg $1 $2

}

createUserForSubOrg(){
	now=`date +%Y-%m-%d.%H:%M:%S%z`
	local query="Insert into sunbird.user (id, channel, email, emailverified , firstName, rootorgid,status,username,roles,createddate) values ('user-$1-$2-1',channel$1,'user-$1-$2-1@gmaol.com',true,'name-$1-$2-1','root-org-$1',1,'username-$1-$2-1',['Public'],$now);"
	echo $query
	local user_root_org_query="Insert into sunbird.user_org (id, organisationid,userid, hashtagid,orgjoindate,roles,isdeleted ) values ('user-org-sub-root-$1','root-org-$1','user-$1-$2-1','root-org-$1',$now,['Public'],false);"
	local user_sub_org_query="Insert into sunbird.user_org (id, organisationid,userid, hashtagid,orgjoindate,roles,isdeleted ) values ('user-sub-org-$1','school-$1-$2','user-$1-$2-1','school-$1-$2',$now,['Public'],false);"
	
	# echo $rootOrgSize
	if [ $1 == 1 ]
	then
		echo $query > $userfile
		echo $user_root_org_query > $userorgfile
		echo $user_sub_org_query >> $userorgfile
	else
		echo $user_root_org_query >> $userorgfile
		echo $user_sub_org_query >> $userorgfile
		echo $query >> $userfile
	fi		
}

createUserForRootOrg(){
	now=`date +%Y-%m-%d.%H:%M:%S%z`
	local query="Insert into sunbird.user (id, channel, email, emailverified , firstName, rootorgid,status,username,roles,createddate) values ('user-$1-$2',channel$1,'user-$1-$2@gmaol.com',true,'name-$1-$2','root-org-$1',1,'username-$1-$2',['Public'],$now);"
	echo $query
	echo $query >> $userfile

	local user_root_org_query="Insert into sunbird.user_org (id, organisationid,userid, hashtagid,orgjoindate,roles,isdeleted ) values ('user-org-root-$1','root-org-$1','user-$1-$2',root-org-$1,$now,['Public'],false);"
	echo $user_root_org_query >> $userorgfile
	
}

createUserForRootOrgAsCreator(){
	now=`date +%Y-%m-%d.%H:%M:%S%z`
	local query="Insert into sunbird.user (id, channel, email, emailverified , firstName, rootorgid,status,username,roles,createddate) values ('user-creator-$1-$2',channel$1,'user-$1-$2@gmaol.com',true,'name-$1-$2','root-org-$1',1,'username-$1-$2',['Public','BOOK_CREATOR','CONTENT_CREATOR'],$now);"
	echo $query
	echo $query >> $userfile
	local user_root_org_query="Insert into sunbird.user_org (id, organisationid,userid, hashtagid,orgjoindate,roles,isdeleted ) values ('user-org-root-creator-$1-$2','root-org-$1','user-creator-$1-$2','root-org-$1',$now,['Public','BOOK_CREATOR','CONTENT_CREATOR'],false);"
	echo $user_root_org_query >> $userorgfile
}
rootOrgSize="$1"
subOrgSize="$2"
rootOrgUserSize="$3"
orgfile="$4"
userfile="$5"
userorgfile="$6"
start
